name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Setup .env
        run: |
          cp .env.example .env
          echo "STANDARD_USERNAME=${{ secrets.STANDARD_USERNAME }}" >> .env
          echo "STANDARD_PASSWORD=${{ secrets.STANDARD_PASSWORD }}" >> .env

      - name: Run E2E tests
        run: npx playwright test

      - name: Upload Playwright HTML Report as Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/

  deploy-report:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Download Playwright Report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy Playwright Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          commit_message: 'Deploy Playwright Report'
